[package]
name = "evildoer-language"
description = "Language configuration and metadata for Evildoer editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cc = "1.0"
evildoer-base.workspace = true
evildoer-manifest.workspace = true
evildoer-runtime.workspace = true
kdl.workspace = true
libloading.workspace = true
once_cell.workspace = true
tracing.workspace = true
regex.workspace = true
ropey.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tree-house.workspace = true

[dev-dependencies]
tempfile.workspace = true
