[package]
name = "xeno-registry-motions"
description = "Motion registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
linkme.workspace = true
paste.workspace = true
regex.workspace = true
ropey.workspace = true
unicode-segmentation.workspace = true
xeno-primitives.workspace = true
xeno-registry-core.workspace = true

[lints]
workspace = true
