[package]
name = "xeno-registry-commands"
description = "Command registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
inventory.workspace = true
paste.workspace = true
thiserror.workspace = true
xeno-registry-core.workspace = true
xeno-registry-motions.workspace = true
xeno-registry-notifications.workspace = true
xeno-registry-textobj.workspace = true

[lints]
workspace = true
