[package]
name = "xeno-input"
description = "Input handling and state machine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
tracing.workspace = true
xeno-base.workspace = true
xeno-core.workspace = true
xeno-keymap.workspace = true
xeno-registry.workspace = true
[dev-dependencies]
