[package]
name = "evildoer-input"
description = "Input handling and state machine for Evildoer editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
log.workspace = true
serde.workspace = true
evildoer-base.workspace = true
evildoer-manifest.workspace = true

[dev-dependencies]
evildoer-stdlib.workspace = true
