[package]
name = "evildoer-input"
description = "Input handling and state machine for Evildoer editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
evildoer-base.workspace = true
evildoer-keymap.workspace = true
evildoer-manifest.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
evildoer-stdlib.workspace = true
