[package]
authors = ["The Nushell Project Developers"]
description = "Nushell's internal protocols, including its abstract syntax tree"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-protocol"
edition = "2024"
license = "MIT"
name = "xeno-nu-protocol"
version = "0.110.1"

[package.metadata.docs.rs]
all-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[features]
default = []
# enables SQLite history
sqlite = []
# enables the Nu profiler implementation
profiler = ["dep:web-time"]

[dependencies]

bytes = { workspace = true }
chrono = { workspace = true, features = ["serde", "std", "unstable-locales"], default-features = false }
chrono-humanize = { workspace = true }
fancy-regex = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
miette = { workspace = true, features = ["fancy-no-backtrace"] }
num-format = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
typetag = "0.2"
web-time = { workspace = true, optional = true }
xeno-nu-derive-value = { path = "../derive-value", version = "0.110.1" }
xeno-nu-experimental = { path = "../experimental", version = "0.110.1" }
xeno-nu-glob = { path = "../glob", version = "0.110.1" }
xeno-nu-path = { path = "../path", version = "0.110.1" }
xeno-nu-utils = { path = "../utils", version = "0.110.1", default-features = false }

[target.'cfg(windows)'.dependencies]
dirs-sys = { workspace = true }
windows = { workspace = true }
windows-sys = { workspace = true, features = ["Win32_UI_Shell"] }

[dev-dependencies]
rstest = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
xeno-nu-utils = { path = "../utils", version = "0.110.1" }

[lints]
workspace = true
