[package]
authors = ["The Nushell Project Developers"]
description = "Nushell's internal protocols, including its abstract syntax tree"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-protocol"
edition = "2024"
license = "MIT"
name = "xeno-nu-protocol"
version = "0.110.1"

[package.metadata.docs.rs]
all-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[features]
default = ["os"]
os = ["xeno-nu-utils/os", "os_pipe"]

plugin = ["brotli", "os", "rmp-serde"]
# enables SQLite history
sqlite = []

[dependencies]

brotli = { workspace = true, optional = true }
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde", "std", "unstable-locales"], default-features = false }
chrono-humanize = { workspace = true }
dirs = { workspace = true }
fancy-regex = { workspace = true }
heck = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
memchr = { workspace = true }
miette = { workspace = true, features = ["fancy-no-backtrace"] }
num-format = { workspace = true }
os_pipe = { workspace = true, optional = true, features = ["io_safety"] }
rmp-serde = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
typetag = "0.2"
web-time = { workspace = true }
xeno-nu-derive-value = { path = "../derive-value", version = "0.110.1" }
xeno-nu-experimental = { path = "../experimental", version = "0.110.1" }
xeno-nu-glob = { path = "../glob", version = "0.110.1" }
xeno-nu-path = { path = "../path", version = "0.110.1" }
xeno-nu-system = { path = "../system", version = "0.110.1" }
xeno-nu-utils = { path = "../utils", version = "0.110.1", default-features = false }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, default-features = false, features = ["signal"] }

[target.'cfg(windows)'.dependencies]
dirs-sys = { workspace = true }
windows = { workspace = true }
windows-sys = { workspace = true, features = ["Win32_UI_Shell"] }

[dev-dependencies]
os_pipe = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
xeno-nu-utils = { path = "../utils", version = "0.110.1" }

[lints]
workspace = true
