[package]
name = "xeno-registry-themes"
description = "Theme and syntax highlighting registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
linkme.workspace = true
strsim.workspace = true
xeno-primitives.workspace = true
xeno-registry-core.workspace = true

[lints]
workspace = true
