[package]
authors = ["The Nushell Project Developers"]
description = "The foundation tools to build Nushell commands."
edition = "2024"
license = "MIT"
name = "xeno-nu-cmd-base"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-cmd-base"
version = "0.110.1"

[dependencies]

indexmap = { workspace = true }
miette = { workspace = true }
xeno-nu-engine = { path = "../engine", version = "0.110.1", default-features = false }
xeno-nu-parser = { path = "../parser", version = "0.110.1" }
xeno-nu-path = { path = "../path", version = "0.110.1" }
xeno-nu-protocol = { path = "../protocol", version = "0.110.1", default-features = false }

[dev-dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true
