[package]
name = "helix-macros"
version = "0.1.7"
edition.workspace = true
authors = ["HelixDB Team"]
repository = "https://github.com/HelixDB/helix-db"
license = "AGPL-3.0"
description = "Proc macros for HelixDB"

[lib]
proc-macro = true

[features]
debug-output = []
default = []

[dependencies]
dirs = "6.0"
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
trybuild = "1.0"
