[package]
name = "xeno-broker-bin"
description = "Xeno broker binary"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "xeno-broker"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
xeno-broker.workspace = true
xeno-broker-proto.workspace = true

[lints]
workspace = true
