[package]
name = "xeno-registry-textobj"
description = "Text objects registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
paste.workspace = true
ropey.workspace = true
xeno-primitives.workspace = true
xeno-registry-core.workspace = true
xeno-registry-motions.workspace = true

[lints]
workspace = true
