[package]
name = "xeno-nu-core"
description = "Internal Nu core wrappers for Xeno"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
xeno-nu-protocol.workspace = true
xeno-nu-sandbox.workspace = true
xeno-nu-value.workspace = true

[lints]
workspace = true
