[package]
name = "xeno-keymap-parser"
description = "Parser for declarative key mapping configurations with support for sequences and key groups."
version.workspace = true
edition.workspace = true
license-file = "../LICENSE"
repository.workspace = true

[dependencies]
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true

[dev-dependencies]
toml = { workspace = true }
