[package]
name = "evildoer-keymap-derive"
description = "Derive macro for compile-time validated key mappings."
version.workspace = true
edition.workspace = true
license-file = "../LICENSE"
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
evildoer-keymap-parser = { path = "../parser" }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
evildoer-keymap = { path = "../" }
serde = { workspace = true }
toml = { workspace = true }
