[package]
name = "xeno-keymap-derive"
description = "Derive macro for compile-time validated key mappings."
version.workspace = true
edition.workspace = true
license-file = "../LICENSE"
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
xeno-keymap-parser = { path = "../parser" }

[dev-dependencies]
serde = { workspace = true }
toml = { workspace = true }
xeno-keymap-core = { path = "../core" }
