[package]
name = "xeno-registry-hooks"
description = "Hook registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
inventory.workspace = true
paste.workspace = true
tracing.workspace = true
xeno-macro.workspace = true
xeno-primitives.workspace = true
xeno-registry-core.workspace = true

[lints]
workspace = true
