[package]
name = "evildoer-registry-options"
description = "Options registry for Evildoer editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
evildoer-registry-motions.workspace = true
linkme.workspace = true
paste.workspace = true
