[package]
name = "xeno-registry-options"
description = "Options registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
inventory.workspace = true
strsim.workspace = true
xeno-macro.workspace = true
xeno-registry-core.workspace = true

[lints]
workspace = true
