[package]
name = "tome-term"
description = "Terminal frontend for Tome editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tome"
path = "src/main.rs"

[dependencies]
clap.workspace = true
linkme.workspace = true
portable-pty = "0.9.0"
ratatui.workspace = true
strsim = "0.11"
termina.workspace = true
tome-core = { workspace = true }
tui-term = "0.2.0"

[dev-dependencies]
insta.workspace = true
kitty-test-harness.workspace = true
serial_test.workspace = true
termwiz = "0.23"
