[package]
name = "tome-term"
description = "Terminal frontend for Tome editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tome"
path = "src/main.rs"

[dependencies]
strsim = "0.11"
linkme.workspace = true
clap.workspace = true
ratatui.workspace = true
termina.workspace = true
tome-core = { workspace = true }

[dev-dependencies]
insta.workspace = true
kitty-test-harness.workspace = true
serial_test.workspace = true
termwiz = "0.23"
