[package]
name = "xeno-term"
description = "Terminal frontend"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "xeno"

[[bin]]
name = "xeno"
path = "src/main.rs"

[features]
perf = ["xeno-editor-tui/perf"]
lsp = ["xeno-editor/lsp"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
uuid.workspace = true
which.workspace = true
xeno-editor = { workspace = true, features = ["tui"] }
xeno-editor-tui.workspace = true
xeno-language.workspace = true

[dev-dependencies]
kitty-test-harness = "0.3"
serde_json.workspace = true
serial_test.workspace = true
termwiz.workspace = true

[lints]
workspace = true
