[package]
name = "evildoer-theme"
description = "Theme definitions and color logic for Evildoer editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
linkme.workspace = true
serde.workspace = true
strsim.workspace = true
evildoer-base.workspace = true
evildoer-manifest.workspace = true
