[package]
name = "xeno-registry-actions"
description = "Actions registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
handler-coverage = []

[dependencies]
linkme.workspace = true
paste.workspace = true
ropey.workspace = true
tracing.workspace = true
xeno-macro.workspace = true
xeno-primitives.workspace = true
xeno-registry-commands.workspace = true
xeno-registry-core.workspace = true
xeno-registry-motions.workspace = true
xeno-registry-notifications.workspace = true
xeno-registry-options.workspace = true
xeno-registry-textobj.workspace = true

[lints]
workspace = true
