[package]
name = "xeno-registry-core"
description = "Shared registry infrastructure"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
inventory.workspace = true
thiserror.workspace = true

[lints]
workspace = true
