[package]
name = "tree-house"
description = "Tree-sitter syntax and highlighting integration"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []

[dependencies]
arc-swap.workspace = true
hashbrown.workspace = true
kstring.workspace = true
once_cell.workspace = true
regex.workspace = true
regex-cursor.workspace = true
ropey.workspace = true
slab.workspace = true
tree-sitter = { workspace = true, features = ["ropey"] }

[lints]
workspace = true
