[package]
name = "xeno-tree-house"
description = "Tree-sitter syntax and highlighting integration"
version.workspace = true
edition.workspace = true
license-file = "./LICENSE"
repository.workspace = true
rust-version.workspace = true

[features]
default = []

[dependencies]
arc-swap.workspace = true
regex.workspace = true
regex-cursor.workspace = true
ropey.workspace = true
slab.workspace = true
tree-sitter = { workspace = true, features = ["ropey"] }

[lints]
workspace = true
