[package]
name = "xeno-tui"
version.workspace = true
authors = ["The Ratatui Developers", "Albert O'Shea"]
edition.workspace = true
description = "TUI library"
license.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["underline-color", "macros", "scrolling-regions"]
underline-color = []
macros = []
palette = ["dep:palette"]
serde = ["dep:serde", "bitflags/serde", "compact_str/serde"]
scrolling-regions = []

[dependencies]
anstyle = { version = "1", optional = true }
bitflags = "2.10"
compact_str = "0.9"

palette = { version = "0.7", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }

unicode-segmentation = "1"
unicode-truncate = "2"
unicode-width = ">=0.2.0, <=0.2.2"
vt100 = "0.16"

[dev-dependencies]
indoc = "2.0"
pretty_assertions = "1.4"
rstest = "0.26"
serde_json = "1.0"

[lints]
workspace = true
