[package]
authors = ["The Nushell Project Developers"]
description = "Nushell utility functions"
edition = "2024"
license = "MIT"
name = "xeno-nu-utils"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-utils"
version = "0.110.1"

[lib]
bench = false

[features]
default = ["os"]
os = ["crossterm"]

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, default-features = false, features = ["user", "fs"] }

[target.'cfg(windows)'.dependencies]
crossterm_winapi = "0.9"

[dependencies]
byteyarn.workspace = true
crossterm = { workspace = true, optional = true }
fancy-regex = { workspace = true }
lean_string.workspace = true
log = { workspace = true }
lscolors = { workspace = true, default-features = false, features = ["nu-ansi-term"] }
memchr = { workspace = true }
num-format = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strip-ansi-escapes = { workspace = true }
sys-locale = "0.3"
unicase = "2.9.0"

[lints]
workspace = true
