[package]
authors = ["The Nushell Project Developers"]
description = "Nushell utility functions"
edition = "2024"
license = "MIT"
name = "xeno-nu-utils"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-utils"
version = "0.110.1"

[lib]
bench = false

[dependencies]
fancy-regex = { workspace = true }
memchr = { workspace = true }
num-format = { workspace = true }
serde = { workspace = true, features = ["derive"] }
strip-ansi-escapes = { workspace = true }
sys-locale = "0.3"
unicase = "2.9.0"

[target.'cfg(windows)'.dependencies]
crossterm_winapi = "0.9"

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
