[package]
name = "tome-acp-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
agent-client-protocol = { workspace = true }
crossbeam-channel = "0.5"
futures = "0.3"
once_cell = "1.19"
parking_lot = "0.12"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tome-cabi-types = { path = "../tome-cabi-types" }
