[package]
name = "xeno-runtime-language"
description = "Language configuration and metadata"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
cc.workspace = true
helix-db.workspace = true
kdl.workspace = true
once_cell.workspace = true
postcard.workspace = true
regex.workspace = true
ropey.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
tree-house.workspace = true
xeno-primitives.workspace = true
xeno-registry.workspace = true
xeno-runtime-data.workspace = true

[build-dependencies]
kdl.workspace = true
postcard.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints.rust]
unused_crate_dependencies = "warn"
