[package]
name = "xeno-runtime-language"
description = "Language configuration and metadata"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cc = "1.2"
kdl.workspace = true
libloading.workspace = true
once_cell.workspace = true
regex.workspace = true
ropey.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tree-house.workspace = true
xeno-base.workspace = true
xeno-core.workspace = true
xeno-registry-themes.workspace = true
xeno-runtime-data.workspace = true

[dev-dependencies]
tempfile.workspace = true
