[package]
authors = ["The Nushell Project Developers"]
description = "Support for the NUON format."
repository = "https://github.com/nushell/nushell/tree/main/crates/nuon"
edition = "2024"
license = "MIT"
name = "xeno-nu-nuon"
version = "0.110.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xeno-nu-parser = { path = "../parser", version = "0.110.1" }
xeno-nu-protocol = { path = "../protocol", version = "0.110.1", default-features = false }

[lints]
workspace = true
