[package]
name = "xeno-keymap-core"
description = "Core key mapping types and pattern matching."
version.workspace = true
edition.workspace = true
license-file = "../LICENSE"
repository.workspace = true

[lib]
doctest = false

[features]
default = ["xeno-primitives"]
xeno-primitives = ["dep:xeno-primitives"]

[dependencies]
xeno-keymap-parser.workspace = true
xeno-primitives = { workspace = true, optional = true }

[lints]
workspace = true
