[package]
name = "xeno-keymap-core"
description = "Core key mapping types and pattern matching."
version.workspace = true
edition.workspace = true
license-file = "../LICENSE"
repository.workspace = true

[lib]
doctest = false

[features]
default = ["termina", "kdl", "xeno-base"]
termina = ["dep:termina"]
kdl = ["dep:kdl"]
xeno-base = ["dep:xeno-base"]

[dependencies]
kdl = { workspace = true, optional = true }
serde = { workspace = true }
termina = { workspace = true, optional = true }
xeno-base = { workspace = true, optional = true }
xeno-keymap-parser = { path = "../parser" }

[dev-dependencies]
toml = { workspace = true }
