[package]
name = "xeno-keymap-core"
description = "Core key mapping types and pattern matching."
version.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
xeno-keymap-parser.workspace = true

[lints]
workspace = true
