[package]
authors = ["The Nushell Project Developers"]
description = "Nushell's parser"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-parser"
edition = "2024"
license = "MIT"
name = "xeno-nu-parser"
version = "0.110.1"
exclude = ["/fuzz"]

[lib]
bench = false

[features]
plugin = []

[dependencies]

bytesize = { workspace = true }
chrono = { default-features = false, features = ['std'], workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
xeno-nu-engine = { path = "../engine", version = "0.110.1", default-features = false }
xeno-nu-path = { path = "../path", version = "0.110.1" }
xeno-nu-protocol = { path = "../protocol", version = "0.110.1", default-features = false }
xeno-nu-utils = { path = "../utils", version = "0.110.1", default-features = false }

[dev-dependencies]
rstest = { workspace = true, default-features = false }

[lints]
workspace = true
